행렬분해는 인수분해랑 같은 것이다. 

In [2]:
import numpy as np

In [3]:
R = np.array([[4, np.NaN, np.NaN, 2, np.NaN],
             [np.NaN, 5, np.NaN, 3, 1],
             [np.NaN, np.NaN, 3, 4, 4],
             [5, 2, 1, 2, np.NaN]])
num_users, num_items = R.shape
K=3

np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [4]:
R

array([[ 4., nan, nan,  2., nan],
       [nan,  5., nan,  3.,  1.],
       [nan, nan,  3.,  4.,  4.],
       [ 5.,  2.,  1.,  2., nan]])

In [5]:
P

array([[ 0.54144845, -0.2039188 , -0.17605725],
       [-0.35765621,  0.28846921, -0.76717957],
       [ 0.58160392, -0.25373563,  0.10634637],
       [-0.08312346,  0.48736931, -0.68671357]])

In [6]:
Q

array([[-0.1074724 , -0.12801812,  0.37792315],
       [-0.36663042, -0.05747607, -0.29261947],
       [ 0.01407125,  0.19427174, -0.36687306],
       [ 0.38157457,  0.30053024,  0.16749811],
       [ 0.30028532, -0.22790929, -0.04096341]])

In [8]:
from sklearn.metrics import mean_squared_error

In [9]:
def get_rmse(R, P, Q, non_zeros):
    error = 0
    
    full_pred_matrix = np.dot(P, Q.T)
    
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

In [13]:
non_zeros = [ (i, j, R[i, j]) for i in range(num_users) for j in range(num_items) if R[i, j] > 0 ]

steps = 1000
learning_rate = 0.01
r_lambda = 0.01

for step in range(steps):
    for i, j, r in non_zeros:
        eij = r - np.dot(P[i, :], Q[j, :].T)
        
        P[i, :] = P[i, :] + learning_rate*(eij * Q[j, :] - r_lambda*P[i, :])
        print('\nP값\n',P[i,:])
        Q[j, :] = Q[j, :] + learning_rate*(eij * P[i, :] - r_lambda*Q[j, :])
        print('Q값\n',Q[i,:])
        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 50 ) == 0:
            print('### iteration step : ', step, ' rmse : ', rmse)


P값
 [ 0.9064692   0.51216098 -0.80085651]
Q값
 [ 1.58006864  1.59706865 -2.1742043 ]
### iteration step :  0  rmse :  0.015669094513717164

P값
 [ 0.90637409  0.51210948 -0.8007712 ]
Q값
 [ 1.58006864  1.59706865 -2.1742043 ]
### iteration step :  0  rmse :  0.01575127739222004

P값
 [-0.0297755   0.73178755 -2.37591656]
Q값
 [-0.68699152  0.46238652 -1.94455545]
### iteration step :  0  rmse :  0.015593757927126473

P값
 [-0.02958518  0.73172636 -2.37589826]
Q값
 [-0.68699152  0.46238652 -1.94455545]
### iteration step :  0  rmse :  0.015542634844113534

P값
 [-0.02963036  0.7316591  -2.37564456]
Q값
 [-0.68699152  0.46238652 -1.94455545]
### iteration step :  0  rmse :  0.015662659091691167

P값
 [ 2.28150011  0.06905493 -1.23509982]
Q값
 [ 1.08324973 -0.10824854 -0.42391901]
### iteration step :  0  rmse :  0.015675807667292967

P값
 [ 2.28151302  0.06906348 -1.23525859]
Q값
 [ 1.08324973 -0.10824854 -0.42391901]
### iteration step :  0  rmse :  0.015504599341672807

P값
 [ 2.28150298  0.0690298

 [-0.68551125  0.46234536 -1.94588489]

P값
 [-0.02969276  0.73006767 -2.37466713]
Q값
 [-0.68551125  0.46234536 -1.94588489]

P값
 [-0.02973801  0.73000056 -2.37441353]
Q값
 [-0.68551125  0.46234536 -1.94588489]

P값
 [ 2.28005076  0.06827288 -1.23576986]
Q값
 [ 1.08377428 -0.10908725 -0.42396945]

P값
 [ 2.28006366  0.06828135 -1.23592865]
Q값
 [ 1.08377428 -0.10908725 -0.42396945]

P값
 [ 2.28005391  0.0682478  -1.23587811]
Q값
 [ 1.08377428 -0.10908725 -0.42396945]

P값
 [ 0.65142858  1.11150551 -0.99663586]
Q값
 [ 1.06593555  0.06767395 -1.24902472]

P값
 [ 0.6514092   1.11136349 -0.99640628]
Q값
 [ 1.06593555  0.06767395 -1.24902472]

P값
 [ 0.65126613  1.1112602  -0.99627615]
Q값
 [ 1.06593555  0.06767395 -1.24902472]

P값
 [ 0.65105407  1.11113975 -0.99600435]
Q값
 [ 1.06573921  0.06751401 -1.24876252]

P값
 [ 0.90561406  0.5128251  -0.8013004 ]
Q값
 [ 1.57945767  1.59835559 -2.17323097]

P값
 [ 0.90551918  0.51277354 -0.80121521]
Q값
 [ 1.57945767  1.59835559 -2.17323097]

P값
 [-0.0298891   0.73003

 [-0.68377729  0.46229037 -1.94744153]

P값
 [ 2.27835638  0.06735329 -1.23655628]
Q값
 [ 1.08438438 -0.11007161 -0.42403312]

P값
 [ 2.27836928  0.06736167 -1.23671508]
Q값
 [ 1.08438438 -0.11007161 -0.42403312]

P값
 [ 2.27835987  0.06732827 -1.23666451]
Q값
 [ 1.08438438 -0.11007161 -0.42403312]

P값
 [ 0.65247156  1.11192457 -0.99555407]
Q값
 [ 1.0657461   0.06690256 -1.25014083]

P값
 [ 0.65245192  1.11178254 -0.99532462]
Q값
 [ 1.0657461   0.06690256 -1.25014083]

P값
 [ 0.65230878  1.11167927 -0.99519463]
Q값
 [ 1.0657461   0.06690256 -1.25014083]

P값
 [ 0.6520975   1.11155894 -0.9949238 ]
Q값
 [ 1.06555017  0.06674355 -1.24987948]

P값
 [ 0.90466876  0.51356225 -0.80179251]
Q값
 [ 1.57878229  1.59977784 -2.17214254]

P값
 [ 0.90457413  0.51351063 -0.80170744]
Q값
 [ 1.57878229  1.59977784 -2.17214254]

P값
 [-0.0300172   0.72808834 -2.37317686]
Q값
 [-0.6836908   0.46228744 -1.94751915]

P값
 [-0.02982762  0.72802722 -2.3731584 ]
Q값
 [-0.6836908   0.46228744 -1.94751915]

P값
 [-0.02987295  0.72796


P값
 [ 0.6530834   1.11195886 -0.99390482]
Q값
 [ 1.06536896  0.06601934 -1.25093288]

P값
 [ 0.90377544  0.51426183 -0.80225892]
Q값
 [ 1.57814405  1.60112154 -2.17110186]

P값
 [ 0.90368104  0.51421015 -0.80217397]
Q값
 [ 1.57814405  1.60112154 -2.17110186]

P값
 [-0.03014067  0.72625026 -2.37182329]
Q값
 [-0.6820514   0.46222836 -1.94899018]

P값
 [-0.02995145  0.72618917 -2.37180474]
Q값
 [-0.6820514   0.46222836 -1.94899018]

P값
 [-0.02999687  0.72612244 -2.37155136]
Q값
 [-0.6820514   0.46222836 -1.94899018]

P값
 [ 2.27667351  0.06643423 -1.23734069]
Q값
 [ 1.08498691 -0.11105339 -0.42410142]

P값
 [ 2.2766864   0.06644253 -1.23749951]
Q값
 [ 1.08498691 -0.11105339 -0.42410142]

P값
 [ 2.27667733  0.06640928 -1.23744889]
Q값
 [ 1.08498691 -0.11105339 -0.42410142]

P값
 [ 0.65350875  1.11234546 -0.99448043]
Q값
 [ 1.06555491  0.06613952 -1.25124863]

P값
 [ 0.65348885  1.11220342 -0.99425111]
Q값
 [ 1.06555491  0.06613952 -1.25124863]

P값
 [ 0.65334564  1.11210017 -0.99412125]
Q값
 [ 1.06555491  0.06


P값
 [ 2.27508947  0.06553676 -1.23819219]
Q값
 [ 1.08555236 -0.11198368 -0.42417058]

P값
 [ 0.65448874  1.11274692 -0.99346797]
Q값
 [ 1.06537172  0.06542227 -1.2522934 ]

P값
 [ 0.65446859  1.11260488 -0.99323877]
Q값
 [ 1.06537172  0.06542227 -1.2522934 ]

P값
 [ 0.65432532  1.11250165 -0.99310904]
Q값
 [ 1.06537172  0.06542227 -1.2522934 ]

P값
 [ 0.65411557  1.11238154 -0.99284009]
Q값
 [ 1.06517657  0.06526505 -1.25203368]

P값
 [ 0.90284001  0.51499748 -0.80274872]
Q값
 [ 1.57747575  1.6025282  -2.16999951]

P값
 [ 0.90274585  0.51494575 -0.80266389]
Q값
 [ 1.57747575  1.6025282  -2.16999951]

P값
 [-0.03027247  0.72432368 -2.37041004]
Q값
 [-0.68033353  0.46215941 -1.9505309 ]

P값
 [-0.03008363  0.72426263 -2.3703914 ]
Q값
 [-0.68033353  0.46215941 -1.9505309 ]

P값
 [-0.03012913  0.72419609 -2.37013814]
Q값
 [-0.68033353  0.46215941 -1.9505309 ]

P값
 [ 2.27500202  0.06551575 -1.23812309]
Q값
 [ 1.08558194 -0.11203258 -0.42417433]

P값
 [ 2.2750149   0.06552396 -1.23828192]
Q값
 [ 1.08558194 -0.11


P값
 [ 0.65529984  1.11290463 -0.99210408]
Q값
 [ 1.06518702  0.06471238 -1.25333079]

P값
 [ 0.65509083  1.11278462 -0.99183605]
Q값
 [ 1.06499226  0.06455602 -1.25307186]

P값
 [ 0.901956    0.51569566 -0.80321291]
Q값
 [ 1.57684419  1.60385722 -2.16894584]

P값
 [ 0.90186207  0.51564387 -0.80312819]
Q값
 [ 1.57684419  1.60385722 -2.16894584]

P값
 [-0.03039937  0.72250121 -2.36907833]
Q값
 [-0.67870894  0.46208754 -1.95198727]

P값
 [-0.03021089  0.7224402  -2.36905961]
Q값
 [-0.67870894  0.46208754 -1.95198727]

P값
 [-0.03025647  0.72237384 -2.36880645]
Q값
 [-0.67870894  0.46208754 -1.95198727]

P값
 [ 2.27342456  0.06464376 -1.23886452]
Q값
 [ 1.08614029 -0.11296037 -0.42424784]

P값
 [ 2.27343743  0.06465188 -1.23902336]
Q값
 [ 1.08614029 -0.11296037 -0.42424784]

P값
 [ 2.27342902  0.06461893 -1.23897266]
Q값
 [ 1.08614029 -0.11296037 -0.42424784]

P값
 [ 0.65551473  1.11317114 -0.99241005]
Q값
 [ 1.06517726  0.06467522 -1.25338519]

P값
 [ 0.65549432  1.11302909 -0.99218099]
Q값
 [ 1.06517726  0.06


P값
 [ 0.90112266  0.51635648 -0.80365164]
Q값
 [ 1.57624886  1.60510977 -2.16794193]

P값
 [ 0.90102894  0.51630463 -0.80356703]
Q값
 [ 1.57624886  1.60510977 -2.16794193]

P값
 [-0.03052107  0.72078163 -2.3678264 ]
Q값
 [-0.67717644  0.46201381 -1.95336047]

P값
 [-0.03033292  0.72072066 -2.36780761]
Q값
 [-0.67717644  0.46201381 -1.95336047]

P값
 [-0.03037859  0.72065446 -2.36755455]
Q값
 [-0.67717644  0.46201381 -1.95336047]

P값
 [ 2.27193941  0.0638182  -1.23956525]
Q값
 [ 1.08666307 -0.11383712 -0.42432126]

P값
 [ 2.27195228  0.06382625 -1.2397241 ]
Q값
 [ 1.08666307 -0.11383712 -0.42432126]

P값
 [ 2.27194417  0.06379342 -1.23967336]
Q값
 [ 1.08666307 -0.11383712 -0.42432126]

P값
 [ 0.65643325  1.11355429 -0.99146475]
Q값
 [ 1.06500086  0.06400977 -1.25436087]

P값
 [ 0.6564126   1.11341223 -0.99123582]
Q값
 [ 1.06500086  0.06400977 -1.25436087]

P값
 [ 0.65626922  1.11330903 -0.99110634]
Q값
 [ 1.06500086  0.06400977 -1.25436087]

P값
 [ 0.65606093  1.11318913 -0.99083921]
Q값
 [ 1.06480648  0.06


P값
 [ 0.65734717  1.11393865 -0.99052588]
Q값
 [ 1.06482318  0.06335077 -1.25533003]

P값
 [ 0.65732629  1.1137966  -0.99029707]
Q값
 [ 1.06482318  0.06335077 -1.25533003]

P값
 [ 0.65718285  1.11369341 -0.99016771]
Q값
 [ 1.06482318  0.06335077 -1.25533003]

P값
 [ 0.65697526  1.1135736  -0.98990143]
Q값
 [ 1.06462916  0.06319607 -1.2550726 ]

P값
 [ 0.90024738  0.51705337 -0.80411367]
Q값
 [ 1.57562358  1.60642509 -2.16687633]

P값
 [ 0.90015388  0.51700146 -0.80402916]
Q값
 [ 1.57562358  1.60642509 -2.16687633]

P값
 [-0.03065106  0.71897383 -2.36651505]
Q값
 [-0.67556573  0.46193007 -1.9548031 ]

P값
 [-0.03046326  0.71891289 -2.36649617]
Q값
 [-0.67556573  0.46193007 -1.9548031 ]

P값
 [-0.03050901  0.71884687 -2.36624322]
Q값
 [-0.67556573  0.46193007 -1.9548031 ]

P값
 [ 2.27038149  0.06294737 -1.24030314]
Q값
 [ 1.0872084  -0.11476022 -0.42440274]

P값
 [ 2.27039434  0.06295534 -1.24046201]
Q값
 [ 1.0872084  -0.11476022 -0.42440274]

P값
 [ 2.27038656  0.06292266 -1.24041123]
Q값
 [ 1.0872084  -0.11

 [ 2.26892754  0.06213086 -1.24115942]
Q값
 [ 1.08771891 -0.11563248 -0.42448367]

P값
 [ 2.26892005  0.06209831 -1.2411086 ]
Q값
 [ 1.08771891 -0.11563248 -0.42448367]

P값
 [ 0.65830691  1.11434564 -0.98954178]
Q값
 [ 1.06463425  0.06266209 -1.25634602]

P값
 [ 0.65828577  1.11420358 -0.98931311]
Q값
 [ 1.06463425  0.06266209 -1.25634602]

P값
 [ 0.65814229  1.11410041 -0.98918387]
Q값
 [ 1.06463425  0.06266209 -1.25634602]

P값
 [ 0.65793541  1.1139807  -0.98891849]
Q값
 [ 1.06444061  0.06250822 -1.25608935]

P값
 [ 0.89937654  0.51774961 -0.80457456]
Q값
 [ 1.5750015   1.60773346 -2.16580477]

P값
 [ 0.89928326  0.51769764 -0.80449016]
Q값
 [ 1.5750015   1.60773346 -2.16580477]

P값
 [-0.03078257  0.71717349 -2.36521401]
Q값
 [-0.67396206  0.46184033 -1.95623873]

P값
 [-0.03059513  0.7171126  -2.36519505]
Q값
 [-0.67396206  0.46184033 -1.95623873]

P값
 [-0.03064096  0.71704676 -2.36494219]
Q값
 [-0.67396206  0.46184033 -1.95623873]

P값
 [ 2.26883346  0.06207718 -1.24103924]
Q값
 [ 1.0877471  -0.115680


P값
 [ 0.89851012  0.51844521 -0.80503432]
Q값
 [ 1.5743826   1.60903494 -2.16472735]

P값
 [ 0.89841706  0.51839318 -0.80495002]
Q값
 [ 1.5743826   1.60903494 -2.16472735]

P값
 [-0.03091558  0.71538059 -2.36392317]
Q값
 [-0.67236541  0.46174466 -1.9576674 ]

P값
 [-0.03072848  0.71531974 -2.36390413]
Q값
 [-0.67236541  0.46174466 -1.9576674 ]

P값
 [-0.03077439  0.71525407 -2.36365137]
Q값
 [-0.67236541  0.46174466 -1.9576674 ]

P값
 [ 2.26729524  0.06120766 -1.24177352]
Q값
 [ 1.08827921 -0.11659906 -0.42457783]

P값
 [ 2.26730807  0.06121549 -1.24193241]
Q값
 [ 1.08827921 -0.11659906 -0.42457783]

P값
 [ 2.26730091  0.06118309 -1.24188155]
Q값
 [ 1.08827921 -0.11659906 -0.42457783]

P값
 [ 0.65931168  1.11477537 -0.98851352]
Q값
 [ 1.0644339   0.06194475 -1.25740777]

P값
 [ 0.65929028  1.11463331 -0.988285  ]
Q값
 [ 1.0644339   0.06194475 -1.25740777]

P값
 [ 0.65914675  1.11453016 -0.98815589]
Q값
 [ 1.0644339   0.06194475 -1.25740777]

P값
 [ 0.65894063  1.11441054 -0.98789145]
Q값
 [ 1.06424066  0.06


P값
 [ 0.89764809  0.51914018 -0.80549291]
Q값
 [ 1.57376686  1.61032959 -2.16364416]

P값
 [ 0.89755524  0.51908809 -0.80540872]
Q값
 [ 1.57376686  1.61032959 -2.16364416]

P값
 [-0.03105004  0.71359507 -2.36264244]
Q값
 [-0.67077572  0.46164313 -1.95908914]

P값
 [-0.03086328  0.71353427 -2.36262332]
Q값
 [-0.67077572  0.46164313 -1.95908914]

P값
 [-0.03090928  0.71346877 -2.36237067]
Q값
 [-0.67077572  0.46164313 -1.95908914]

P값
 [ 2.26576672  0.06033885 -1.242506  ]
Q값
 [ 1.08880476 -0.11751475 -0.4246714 ]

P값
 [ 2.26577954  0.0603466  -1.2426649 ]
Q값
 [ 1.08880476 -0.11751475 -0.4246714 ]

P값
 [ 2.2657727   0.06031434 -1.24261401]
Q값
 [ 1.08880476 -0.11751475 -0.4246714 ]

P값
 [ 0.66026104  1.11518481 -0.98754388]
Q값
 [ 1.06424219  0.0612704  -1.25840916]

P값
 [ 0.6602394   1.11504274 -0.9873155 ]
Q값
 [ 1.06424219  0.0612704  -1.25840916]

P값
 [ 0.66009582  1.11493961 -0.98718652]
Q값
 [ 1.06424219  0.0612704  -1.25840916]

P값
 [ 0.65989041  1.11482009 -0.98692296]
Q값
 [ 1.06404932  0.06

 [-0.0311931   0.71172352 -2.36130512]
Q값
 [-0.66910984  0.46152998 -1.96057828]

P값
 [-0.0310067   0.71166276 -2.36128591]
Q값
 [-0.66910984  0.46152998 -1.96057828]

P값
 [-0.03105278  0.71159745 -2.36103337]
Q값
 [-0.66910984  0.46152998 -1.96057828]

P값
 [ 2.26416815  0.05942509 -1.24327509]
Q값
 [ 1.08935094 -0.11847591 -0.42477418]

P값
 [ 2.26418096  0.05943277 -1.243434  ]
Q값
 [ 1.08935094 -0.11847591 -0.42477418]

P값
 [ 2.26417444  0.05940066 -1.24338306]
Q값
 [ 1.08935094 -0.11847591 -0.42477418]

P값
 [ 0.66125495  1.11561699 -0.98653075]
Q값
 [ 1.06403897  0.06056797 -1.25945566]

P값
 [ 0.66123304  1.11547492 -0.98630251]
Q값
 [ 1.06403897  0.06056797 -1.25945566]

P값
 [ 0.66108943  1.1153718  -0.98617366]
Q값
 [ 1.06403897  0.06056797 -1.25945566]

P값
 [ 0.66088475  1.11525238 -0.98591103]
Q값
 [ 1.0638465   0.06041668 -1.25920132]

P값
 [ 0.89670039  0.51990757 -0.80599843]
Q값
 [ 1.57308997  1.61175263 -2.16244037]

P값
 [ 0.89660778  0.51985541 -0.80591434]
Q값
 [ 1.57308997  1.611752

 [ 0.89584752  0.52060122 -0.80645456]
Q값
 [ 1.57248083  1.61303308 -2.16134538]

P값
 [ 0.89575512  0.520549   -0.80637057]
Q값
 [ 1.57248083  1.61303308 -2.16134538]

P값
 [-0.03133768  0.70986007 -2.35997879]
Q값
 [-0.66745158  0.46141048 -1.96205983]

P값
 [-0.03115164  0.70979936 -2.35995949]
Q값
 [-0.66745158  0.46141048 -1.96205983]

P값
 [-0.0311978   0.70973423 -2.35970705]
Q값
 [-0.66745158  0.46141048 -1.96205983]

P값
 [ 2.26258013  0.05851218 -1.24404218]
Q값
 [ 1.08988994 -0.11943427 -0.42488134]

P값
 [ 2.26259293  0.05851979 -1.2442011 ]
Q값
 [ 1.08988994 -0.11943427 -0.42488134]

P값
 [ 2.26258673  0.05848782 -1.24415012]
Q값
 [ 1.08988994 -0.11943427 -0.42488134]

P값
 [ 0.66224333  1.11605032 -0.98552528]
Q값
 [ 1.06383432  0.05987306 -1.26049445]

P값
 [ 0.66222116  1.11590825 -0.9852972 ]
Q값
 [ 1.06383432  0.05987306 -1.26049445]

P값
 [ 0.66207751  1.11580515 -0.98516849]
Q값
 [ 1.06383432  0.05987306 -1.26049445]

P값
 [ 0.66187357  1.11568582 -0.98490678]
Q값
 [ 1.06364225  0.059722

 [ 1.06364896  0.05925398 -1.26142282]

P값
 [ 0.66296208  1.11619609 -0.98427035]
Q값
 [ 1.06364896  0.05925398 -1.26142282]

P값
 [ 0.66275879  1.11607683 -0.98400946]
Q값
 [ 1.06345723  0.05910431 -1.26116994]

P값
 [ 0.89499896  0.52129426 -0.80690951]
Q값
 [ 1.5718748   1.61430687 -2.16024494]

P값
 [ 0.89490676  0.52124198 -0.80682561]
Q값
 [ 1.5718748   1.61430687 -2.16024494]

P값
 [-0.03147641  0.70809725 -2.35872885]
Q값
 [-0.66588323  0.46129114 -1.96346033]

P값
 [-0.0312907   0.70803659 -2.35870947]
Q값
 [-0.66588323  0.46129114 -1.96346033]

P값
 [-0.03133695  0.70797163 -2.35845712]
Q값
 [-0.66588323  0.46129114 -1.96346033]

P값
 [ 2.26108119  0.05764572 -1.24476908]
Q값
 [ 1.09039538 -0.12034208 -0.42498717]

P값
 [ 2.26109398  0.05765326 -1.244928  ]
Q값
 [ 1.09039538 -0.12034208 -0.42498717]

P값
 [ 2.26108809  0.05762143 -1.24487699]
Q값
 [ 1.09039538 -0.12034208 -0.42498717]

P값
 [ 0.66317719  1.11646299 -0.98457715]
Q값
 [ 1.06363863  0.05921976 -1.26147421]

P값
 [ 0.66315478  1.11632

 [ 0.66403471  1.11671272 -0.98345744]
Q값
 [ 1.0634521   0.05860695 -1.26239609]

P값
 [ 0.66389099  1.11660964 -0.98332896]
Q값
 [ 1.0634521   0.05860695 -1.26239609]

P값
 [ 0.66368839  1.11649047 -0.98306894]
Q값
 [ 1.06326075  0.05845809 -1.26214394]

P값
 [ 0.89415469  0.52198669 -0.80736325]
Q값
 [ 1.57127186  1.61557406 -2.15913914]

P값
 [ 0.8940627   0.52193434 -0.80727945]
Q값
 [ 1.57127186  1.61557406 -2.15913914]

P값
 [-0.03161643  0.70634166 -2.35748863]
Q값
 [-0.66432167  0.46116619 -1.96485405]

P값
 [-0.03143106  0.70628104 -2.35746917]
Q값
 [-0.66432167  0.46116619 -1.96485405]

P값
 [-0.03147739  0.70621625 -2.35721692]
Q값
 [-0.66432167  0.46116619 -1.96485405]

P값
 [ 2.2595916   0.05678008 -1.24549417]
Q값
 [ 1.09089443 -0.12124731 -0.42509689]

P값
 [ 2.25960437  0.05678756 -1.2456531 ]
Q값
 [ 1.09089443 -0.12124731 -0.42509689]

P값
 [ 2.25959879  0.05675586 -1.24560205]
Q값
 [ 1.09089443 -0.12124731 -0.42509689]

P값
 [ 0.66410612  1.11687657 -0.98363585]
Q값
 [ 1.0634417   0.058573

 [ 1.09138712 -0.12214994 -0.42521048]

P값
 [ 2.25811874  0.05589114 -1.24632532]
Q값
 [ 1.09138712 -0.12214994 -0.42521048]

P값
 [ 0.66503014  1.11729102 -0.98270134]
Q값
 [ 1.06324359  0.05793294 -1.26341324]

P값
 [ 0.66500724  1.11714896 -0.98247372]
Q값
 [ 1.06324359  0.05793294 -1.26341324]

P값
 [ 0.66486348  1.11704589 -0.98234537]
Q값
 [ 1.06324359  0.05793294 -1.26341324]

P값
 [ 0.6646616   1.11692681 -0.98208626]
Q값
 [ 1.06305263  0.05778492 -1.26316185]

P값
 [ 0.89327059  0.5227149  -0.80783957]
Q값
 [ 1.5706405   1.61690087 -2.15796946]

P값
 [ 0.89317881  0.5226625  -0.80775587]
Q값
 [ 1.5706405   1.61690087 -2.15796946]

P값
 [-0.03176519  0.70450143 -2.35619353]
Q값
 [-0.6626852   0.46102869 -1.96631386]

P값
 [-0.03158016  0.70444087 -2.356174  ]
Q값
 [-0.6626852   0.46102869 -1.96631386]

P값
 [-0.03162658  0.70437626 -2.35592184]
Q값
 [-0.6626852   0.46102869 -1.96631386]

P값
 [ 2.2580336   0.05586979 -1.24625549]
Q값
 [ 1.09141287 -0.12219737 -0.42521657]

P값
 [ 2.25804636  0.05587

 [ 0.66558113  1.11734217 -0.98115962]
Q값
 [ 1.06285371  0.05715204 -1.26412194]

P값
 [ 0.89243505  0.52340609 -0.80829081]
Q값
 [ 1.57004385  1.61815467 -2.15685297]

P값
 [ 0.89234347  0.52335362 -0.80820721]
Q값
 [ 1.57004385  1.61815467 -2.15685297]

P값
 [-0.03190777  0.70276055 -2.35497298]
Q값
 [-0.66113742  0.46089244 -1.96769382]

P값
 [-0.03172307  0.70270004 -2.35495337]
Q값
 [-0.66113742  0.46089244 -1.96769382]

P값
 [-0.03176957  0.7026356  -2.35470131]
Q값
 [-0.66113742  0.46089244 -1.96769382]

P값
 [ 2.25656291  0.05500591 -1.2469769 ]
Q값
 [ 1.09189891 -0.12309724 -0.4253342 ]

P값
 [ 2.25657566  0.05501325 -1.24713585]
Q값
 [ 1.09189891 -0.12309724 -0.4253342 ]

P값
 [ 2.2565707   0.05498184 -1.24708472]
Q값
 [ 1.09189891 -0.12309724 -0.4253342 ]

P값
 [ 0.6659975   1.11772816 -0.98172493]
Q값
 [ 1.06303378  0.05726609 -1.26442294]

P값
 [ 0.66597434  1.1175861  -0.98149746]
Q값
 [ 1.06303378  0.05726609 -1.26442294]

P값
 [ 0.66583056  1.11748305 -0.98136925]
Q값
 [ 1.06303378  0.057266


P값
 [ 0.89160372  0.52409667 -0.80874083]
Q값
 [ 1.56945022  1.61940204 -2.15573141]

P값
 [ 0.89151234  0.52404414 -0.80865732]
Q값
 [ 1.56945022  1.61940204 -2.15573141]

P값
 [-0.03205155  0.70102678 -2.35376188]
Q값
 [-0.65959629  0.46075077 -1.96906712]

P값
 [-0.03186718  0.70096632 -2.35374218]
Q값
 [-0.65959629  0.46075077 -1.96906712]

P값
 [-0.03191376  0.70090205 -2.35349021]
Q값
 [-0.65959629  0.46075077 -1.96906712]

P값
 [ 2.2551013   0.05414292 -1.24769652]
Q값
 [ 1.09237866 -0.12399447 -0.42545564]

P값
 [ 2.25511404  0.0541502  -1.24785547]
Q값
 [ 1.09237866 -0.12399447 -0.42545564]

P값
 [ 2.25510938  0.05411892 -1.24780431]
Q값
 [ 1.09237866 -0.12399447 -0.42545564]

P값
 [ 0.66691151  1.11814422 -0.9808042 ]
Q값
 [ 1.0628333   0.05663913 -1.26537529]

P값
 [ 0.66688811  1.11800216 -0.9805769 ]
Q값
 [ 1.0628333   0.05663913 -1.26537529]

P값
 [ 0.66674429  1.11789912 -0.9804488 ]
Q값
 [ 1.0628333   0.05663913 -1.26537529]

P값
 [ 0.6665438   1.1177802  -0.98019144]
Q값
 [ 1.0626431   0.05

 [-0.03202011  0.69914899 -2.35247736]
Q값
 [-0.65798119  0.46059587 -1.97050555]

P값
 [-0.03206678  0.6990849  -2.35222549]
Q값
 [-0.65798119  0.46059587 -1.97050555]

P값
 [ 2.25357248  0.0532355  -1.24845208]
Q값
 [ 1.09287693 -0.12493605 -0.42558757]

P값
 [ 2.25358521  0.05324272 -1.24861103]
Q값
 [ 1.09287693 -0.12493605 -0.42558757]

P값
 [ 2.25358086  0.05321158 -1.24855983]
Q값
 [ 1.09287693 -0.12493605 -0.42558757]

P값
 [ 0.6678684   1.11858293 -0.9798422 ]
Q값
 [ 1.06262107  0.055986   -1.2663706 ]

P값
 [ 0.66784474  1.11844089 -0.97961506]
Q값
 [ 1.06262107  0.055986   -1.2663706 ]

P값
 [ 0.6677009   1.11833785 -0.97948709]
Q값
 [ 1.06262107  0.055986   -1.2663706 ]

P값
 [ 0.66750111  1.11821901 -0.97923062]
Q값
 [ 1.06243125  0.05584042 -1.26612139]

P값
 [ 0.89068977  0.52485926 -0.80923678]
Q값
 [ 1.56879762  1.62077328 -2.15448602]

P값
 [ 0.89059861  0.52480666 -0.80915336]
Q값
 [ 1.56879762  1.62077328 -2.15448602]

P값
 [-0.03221182  0.69911874 -2.35243417]
Q값
 [-0.65790062  0.460587

 [ 0.66835813  1.11861455 -0.97837213]
Q값
 [ 1.06223955  0.05525924 -1.2670116 ]

P값
 [ 0.88991043  0.52551232 -0.80966066]
Q값
 [ 1.56824116  1.62194247 -2.1534138 ]

P값
 [ 0.88981946  0.52545967 -0.80957732]
Q값
 [ 1.56824116  1.62194247 -2.1534138 ]

P값
 [-0.03235028  0.6974901  -2.35130514]
Q값
 [-0.65645357  0.46044329 -1.97186531]

P값
 [-0.03216656  0.69742974 -2.35128528]
Q값
 [-0.65645357  0.46044329 -1.97186531]

P값
 [-0.03221331  0.69736582 -2.3510335 ]
Q값
 [-0.65645357  0.46044329 -1.97186531]

P값
 [ 2.25212925  0.05237443 -1.24916802]
Q값
 [ 1.09334391 -0.12582779 -0.42571675]

P값
 [ 2.25214196  0.05238159 -1.24932699]
Q값
 [ 1.09334391 -0.12582779 -0.42571675]

P값
 [ 2.25213791  0.05235059 -1.24927575]
Q값
 [ 1.09334391 -0.12582779 -0.42571675]

P값
 [ 0.6687725   1.11900038 -0.97893506]
Q값
 [ 1.06241833  0.05537191 -1.26730942]

P값
 [ 0.6687486   1.11885834 -0.97870809]
Q값
 [ 1.06241833  0.05537191 -1.26730942]

P값
 [ 0.66860474  1.11875531 -0.97858024]
Q값
 [ 1.06241833  0.055371

 [ 0.66960047  1.11925438 -0.9778549 ]
Q값
 [ 1.06222529  0.05479583 -1.26819281]

P값
 [ 0.66945659  1.11915137 -0.97772717]
Q값
 [ 1.06222529  0.05479583 -1.26819281]

P값
 [ 0.66925809  1.11903266 -0.97747233]
Q값
 [ 1.06203618  0.05465176 -1.26794493]

P값
 [ 0.88909184  0.5262011  -0.81010686]
Q값
 [ 1.56765669  1.62317051 -2.15227736]

P값
 [ 0.88900106  0.52614838 -0.81002361]
Q값
 [ 1.56765669  1.62317051 -2.15227736]

P값
 [-0.0324975   0.69577779 -2.35012232]
Q값
 [-0.65493248  0.46028548 -1.97321852]

P값
 [-0.0323141   0.69571748 -2.35010239]
Q값
 [-0.65493248  0.46028548 -1.97321852]

P값
 [-0.03236093  0.69565373 -2.3498507 ]
Q값
 [-0.65493248  0.46028548 -1.97321852]

P값
 [ 2.25069484  0.05151432 -1.24988218]
Q값
 [ 1.09380474 -0.12671684 -0.42584967]

P값
 [ 2.25070753  0.05152143 -1.25004115]
Q값
 [ 1.09380474 -0.12671684 -0.42584967]

P값
 [ 2.25070378  0.05149056 -1.24998988]
Q값
 [ 1.09380474 -0.12671684 -0.42584967]

P값
 [ 0.66967182  1.11941844 -0.97803449]
Q값
 [ 1.06221454  0.054763

 [ 0.88822954  0.5268003  -0.81044525]
Q값
 [ 1.56710571  1.62432816 -2.1511964 ]

P값
 [-0.03263796  0.69416202 -2.34901014]
Q값
 [-0.65349742  0.4601312  -1.97449452]

P값
 [-0.03245485  0.69410176 -2.34899014]
Q값
 [-0.65349742  0.4601312  -1.97449452]

P값
 [-0.03250176  0.69403816 -2.34873853]
Q값
 [-0.65349742  0.4601312  -1.97449452]

P값
 [ 2.24934399  0.0507004  -1.25055711]
Q값
 [ 1.09423566 -0.1275566  -0.425979  ]

P값
 [ 2.24935667  0.05070746 -1.25071608]
Q값
 [ 1.09423566 -0.1275566  -0.425979  ]

P값
 [ 2.24935319  0.05067672 -1.25066478]
Q값
 [ 1.09423566 -0.1275566  -0.425979  ]

P값
 [ 0.67051941  1.119815   -0.97718731]
Q값
 [ 1.06202052  0.05419367 -1.26911898]

P값
 [ 0.67049503  1.11967297 -0.97696066]
Q값
 [ 1.06202052  0.05419367 -1.26911898]

P값
 [ 0.67035113  1.11956997 -0.97683304]
Q값
 [ 1.06202052  0.05419367 -1.26911898]

P값
 [ 0.67015328  1.11945133 -0.97657904]
Q값
 [ 1.06183177  0.05405036 -1.26887178]

P값
 [ 0.88827738  0.52688928 -0.8105518 ]
Q값
 [ 1.56707517  1.624392

 [ 1.56652698  1.62554411 -2.15005091]

P값
 [-0.03278722  0.69246321 -2.34784495]
Q값
 [-0.6519889   0.45996338 -1.9758351 ]

P값
 [-0.03260443  0.69240301 -2.34782487]
Q값
 [-0.6519889   0.45996338 -1.9758351 ]

P값
 [-0.03265142  0.69233958 -2.34757335]
Q값
 [-0.6519889   0.45996338 -1.9758351 ]

P값
 [ 2.24792653  0.04984226 -1.2512678 ]
Q값
 [ 1.09468459 -0.12844034 -0.4261191 ]

P값
 [ 2.2479392   0.04984926 -1.25142677]
Q값
 [ 1.09468459 -0.12844034 -0.4261191 ]

P값
 [ 2.24793601  0.04981865 -1.25137543]
Q값
 [ 1.09468459 -0.12844034 -0.4261191 ]

P값
 [ 0.67140947  1.1202341  -0.97629937]
Q값
 [ 1.06181474  0.05359754 -1.27003875]

P값
 [ 0.67138485  1.12009208 -0.97607288]
Q값
 [ 1.06181474  0.05359754 -1.27003875]

P값
 [ 0.67124094  1.11998908 -0.97594539]
Q값
 [ 1.06181474  0.05359754 -1.27003875]

P값
 [ 0.67104373  1.11987051 -0.97569221]
Q값
 [ 1.06162635  0.05345498 -1.26979221]

P값
 [ 0.88746702  0.52757687 -0.81099546]
Q값
 [ 1.5664966   1.62560794 -2.14999049]

P값
 [ 0.88737662  0.52752

 [ 0.6723164   1.12053375 -0.97514531]
Q값
 [ 1.06159707  0.05297645 -1.27100005]

P값
 [ 0.67217248  1.12043076 -0.97501795]
Q값
 [ 1.06159707  0.05297645 -1.27100005]

P값
 [ 0.67197595  1.12031226 -0.97476563]
Q값
 [ 1.06140906  0.05283469 -1.27075422]

P값
 [ 0.88661842  0.52830001 -0.81146108]
Q값
 [ 1.56589074  1.62688093 -2.14877958]

P값
 [ 0.88652822  0.52824711 -0.81137809]
Q값
 [ 1.56589074  1.62688093 -2.14877958]

P값
 [-0.03295337  0.69059359 -2.34656749]
Q값
 [-0.65032903  0.45977202 -1.9773093 ]

P값
 [-0.03277092  0.69053344 -2.34654732]
Q값
 [-0.65032903  0.45977202 -1.9773093 ]

P값
 [-0.032818    0.6904702  -2.34629589]
Q값
 [-0.65032903  0.45977202 -1.9773093 ]

P값
 [ 2.24636985  0.04889499 -1.25205122]
Q값
 [ 1.09517375 -0.12941392 -0.4262782 ]

P값
 [ 2.2463825   0.04890194 -1.2522102 ]
Q값
 [ 1.09517375 -0.12941392 -0.4262782 ]

P값
 [ 2.24637964  0.04887147 -1.25215882]
Q값
 [ 1.09517375 -0.12941392 -0.4262782 ]

P값
 [ 0.67238773  1.12069786 -0.97532542]
Q값
 [ 1.06158616  0.052945


P값
 [ 0.88572641  0.52893343 -0.81181919]
Q값
 [ 1.56531815  1.62808404 -2.14762468]

P값
 [-0.03310472  0.68890922 -2.34542099]
Q값
 [-0.64883393  0.45959364 -1.97863637]

P값
 [-0.03292257  0.68884913 -2.34540075]
Q값
 [-0.64883393  0.45959364 -1.97863637]

P값
 [-0.03296974  0.68878605 -2.34514941]
Q값
 [-0.64883393  0.45959364 -1.97863637]

P값
 [ 2.24497037  0.04803906 -1.25275816]
Q값
 [ 1.09560999 -0.13029187 -0.42642595]

P값
 [ 2.24498301  0.04804595 -1.25291714]
Q값
 [ 1.09560999 -0.13029187 -0.42642595]

P값
 [ 2.24498044  0.04801562 -1.25286573]
Q값
 [ 1.09560999 -0.13029187 -0.42642595]

P값
 [ 0.67326789  1.1211179  -0.97445094]
Q값
 [ 1.06137834  0.05236187 -1.27195437]

P값
 [ 0.67324276  1.1209759  -0.97422482]
Q값
 [ 1.06137834  0.05236187 -1.27195437]

P값
 [ 0.67309883  1.12087291 -0.97409758]
Q값
 [ 1.06137834  0.05236187 -1.27195437]

P값
 [ 0.67290297  1.12075448 -0.97384612]
Q값
 [ 1.06119071  0.05222089 -1.27170923]

P값
 [ 0.88577432  0.52902251 -0.81192527]
Q값
 [ 1.56528809  1.62

 [ 0.88488676  0.52965523 -0.8122821 ]
Q값
 [ 1.56471854  1.62934395 -2.1464043 ]

P값
 [-0.03326505  0.68714354 -2.3442236 ]
Q값
 [-0.64726696  0.45940053 -1.98002642]

P값
 [-0.03308322  0.68708351 -2.34420328]
Q값
 [-0.64726696  0.45940053 -1.98002642]

P값
 [-0.03313048  0.68702061 -2.34395203]
Q값
 [-0.64726696  0.45940053 -1.98002642]

P값
 [ 2.24350634  0.04713925 -1.25350039]
Q값
 [ 1.09606275 -0.13121302 -0.42658536]

P값
 [ 2.24351896  0.04714609 -1.25365937]
Q값
 [ 1.09606275 -0.13121302 -0.42658536]

P값
 [ 2.24351669  0.04711589 -1.25360793]
Q값
 [ 1.09606275 -0.13121302 -0.42658536]

P값
 [ 0.67418933  1.12156045 -0.97353728]
Q값
 [ 1.06115859  0.05175372 -1.27290177]

P값
 [ 0.67416395  1.12141846 -0.97331133]
Q값
 [ 1.06115859  0.05175372 -1.27290177]

P값
 [ 0.67402001  1.12131548 -0.97318422]
Q값
 [ 1.06115859  0.05175372 -1.27290177]

P값
 [ 0.67382482  1.12119712 -0.97293361]
Q값
 [ 1.06097133  0.05161352 -1.27265731]

P값
 [ 0.8849347   0.52974435 -0.81238802]
Q값
 [ 1.56468864  1.629406


P값
 [ 2.24206415  0.04624746 -1.25439963]
Q값
 [ 1.09650895 -0.13213107 -0.42674871]

P값
 [ 2.24206218  0.0462174  -1.25434816]
Q값
 [ 1.09650895 -0.13213107 -0.42674871]

P값
 [ 0.67510563  1.12200338 -0.97263057]
Q값
 [ 1.06093783  0.05115192 -1.2738423 ]

P값
 [ 0.67507999  1.1218614  -0.97240481]
Q값
 [ 1.06093783  0.05115192 -1.2738423 ]

P값
 [ 0.67493605  1.12175843 -0.97227782]
Q값
 [ 1.06093783  0.05115192 -1.2738423 ]

P값
 [ 0.67474152  1.12164013 -0.97202806]
Q값
 [ 1.06075094  0.0510125  -1.27359852]

P값
 [ 0.88409954  0.53046553 -0.81284932]
Q값
 [ 1.56409236  1.63065974 -2.14511785]

P값
 [ 0.88400992  0.53041243 -0.81276659]
Q값
 [ 1.56409236  1.63065974 -2.14511785]

P값
 [-0.03343448  0.68529764 -2.34297668]
Q값
 [-0.64562911  0.45919197 -1.98147842]

P값
 [-0.03325299  0.68523768 -2.34295628]
Q값
 [-0.64562911  0.45919197 -1.98147842]

P값
 [-0.03330033  0.68517495 -2.34270512]
Q값
 [-0.64562911  0.45919197 -1.98147842]

P값
 [ 2.24197904  0.04619577 -1.25427762]
Q값
 [ 1.09653108 -0.13

 [ 0.67560764  1.12206129 -0.97117418]
Q값
 [ 1.06054067  0.05044733 -1.27448636]

P값
 [ 0.88331023  0.53115006 -0.8132862 ]
Q값
 [ 1.56352883  1.63184398 -2.14394954]

P값
 [ 0.8832208   0.53109689 -0.81320355]
Q값
 [ 1.56352883  1.63184398 -2.14394954]

P값
 [-0.0335887   0.68363461 -2.34185755]
Q값
 [-0.6441538   0.45899821 -1.98278552]

P값
 [-0.03340751  0.68357471 -2.34183707]
Q값
 [-0.6441538   0.45899821 -1.98278552]

P값
 [-0.03345494  0.68351215 -2.34158599]
Q값
 [-0.6441538   0.45899821 -1.98278552]

P값
 [ 2.2406059   0.04534334 -1.25497896]
Q값
 [ 1.09694862 -0.13304601 -0.42691598]

P값
 [ 2.24061849  0.04535008 -1.25513793]
Q값
 [ 1.09694862 -0.13304601 -0.42691598]

P값
 [ 2.24061682  0.04532016 -1.25508642]
Q값
 [ 1.09694862 -0.13304601 -0.42691598]

P값
 [ 0.67601681  1.12244664 -0.97173077]
Q값
 [ 1.0607161   0.05055639 -1.27477602]

P값
 [ 0.67599092  1.12230467 -0.97150519]
Q값
 [ 1.0607161   0.05055639 -1.27477602]

P값
 [ 0.67584697  1.1222017  -0.97137833]
Q값
 [ 1.0607161   0.050556

 [ 0.67685159  1.12272605 -0.97065691]
Q값
 [ 1.06050457  0.04999638 -1.27565681]

P값
 [ 0.67670764  1.12262308 -0.97053017]
Q값
 [ 1.06050457  0.04999638 -1.27565681]

P값
 [ 0.67651438  1.1225049  -0.97028205]
Q값
 [ 1.06031841  0.04985845 -1.27541434]

P값
 [ 0.88248368  0.53186997 -0.81374465]
Q값
 [ 1.56293868  1.6330842  -2.14271535]

P값
 [ 0.88239444  0.53181674 -0.81366208]
Q값
 [ 1.56293868  1.6330842  -2.14271535]

P값
 [-0.03375197  0.68189128 -2.34068869]
Q값
 [-0.64260752  0.45878912 -1.98415465]

P값
 [-0.03357109  0.68183143 -2.34066813]
Q값
 [-0.64260752  0.45878912 -1.98415465]

P값
 [-0.03361861  0.68176904 -2.34041714]
Q값
 [-0.64260752  0.45878912 -1.98415465]

P값
 [ 2.23916932  0.04444728 -1.25571529]
Q값
 [ 1.09738181 -0.13395782 -0.42708714]

P값
 [ 2.23918189  0.04445399 -1.25587427]
Q값
 [ 1.09738181 -0.13395782 -0.42708714]

P값
 [ 2.23918053  0.0444242  -1.25582273]
Q값
 [ 1.09738181 -0.13395782 -0.42708714]

P값
 [ 0.6769229   1.12289019 -0.97083783]
Q값
 [ 1.06049342  0.049967


P값
 [-0.03376669  0.68020654 -2.33937315]
Q값
 [-0.64122169  0.45859649 -1.98538099]

P값
 [ 2.23788408  0.04364195 -1.25637633]
Q값
 [ 1.09776618 -0.13477576 -0.42724448]

P값
 [ 2.23789663  0.04364861 -1.2565353 ]
Q값
 [ 1.09776618 -0.13477576 -0.42724448]

P값
 [ 2.23789554  0.04361894 -1.25648373]
Q값
 [ 1.09776618 -0.13477576 -0.42724448]

P값
 [ 0.67773406  1.12328958 -0.97004   ]
Q값
 [ 1.06029222  0.04944189 -1.27653155]

P값
 [ 0.67770769  1.12314764 -0.96981478]
Q값
 [ 1.06029222  0.04944189 -1.27653155]

P값
 [ 0.67756374  1.12304467 -0.96968815]
Q값
 [ 1.06029222  0.04944189 -1.27653155]

P값
 [ 0.6773711   1.12292655 -0.96944083]
Q값
 [ 1.06010641  0.04930468 -1.27628971]

P값
 [ 0.88170252  0.53255329 -0.81417881]
Q값
 [ 1.56238093  1.63425644 -2.14153878]

P값
 [ 0.88161346  0.53249999 -0.81409632]
Q값
 [ 1.56238093  1.63425644 -2.14153878]

P값
 [-0.03390792  0.68024192 -2.33958692]
Q값
 [-0.64114486  0.45858567 -1.98544895]

P값
 [-0.03372734  0.68018214 -2.33956629]
Q값
 [-0.64114486  0.45


P값
 [ 0.88096611  0.53320009 -0.81458888]
Q값
 [ 1.56185512  1.63536164 -2.14042054]

P값
 [ 0.88087722  0.53314673 -0.81450647]
Q값
 [ 1.56185512  1.63536164 -2.14042054]

P값
 [-0.0340564   0.67868547 -2.33855082]
Q값
 [-0.63976481  0.45838865 -1.98666943]

P값
 [-0.03387609  0.67862574 -2.33853012]
Q값
 [-0.63976481  0.45838865 -1.98666943]

P값
 [-0.03392377  0.67856367 -2.33827928]
Q값
 [-0.63976481  0.45838865 -1.98666943]

P값
 [ 2.23653525  0.04279303 -1.25707236]
Q값
 [ 1.09816629 -0.13563637 -0.42741391]

P값
 [ 2.23654779  0.04279965 -1.25723134]
Q값
 [ 1.09816629 -0.13563637 -0.42741391]

P값
 [ 2.23654697  0.04277011 -1.25717973]
Q값
 [ 1.09816629 -0.13563637 -0.42741391]

P값
 [ 0.67858585  1.12371134 -0.96920379]
Q값
 [ 1.06007906  0.04889287 -1.27740031]

P값
 [ 0.67855925  1.12356941 -0.96897875]
Q값
 [ 1.06007906  0.04889287 -1.27740031]

P값
 [ 0.6784153   1.12346645 -0.96885224]
Q값
 [ 1.06007906  0.04889287 -1.27740031]

P값
 [ 0.67822327  1.12334838 -0.9686057 ]
Q값
 [ 1.05989359  0.04


P값
 [ 2.23526476  0.04198991 -1.25773014]
Q값
 [ 1.09854006 -0.13644903 -0.42757759]

P값
 [ 2.23527728  0.04199649 -1.25788911]
Q값
 [ 1.09854006 -0.13644903 -0.42757759]

P값
 [ 2.23527673  0.04196707 -1.25783748]
Q값
 [ 1.09854006 -0.13644903 -0.42757759]

P값
 [ 0.67938864  1.12411104 -0.96841718]
Q값
 [ 1.05987639  0.04837771 -1.27821786]

P값
 [ 0.67936181  1.12396912 -0.96819232]
Q값
 [ 1.05987639  0.04837771 -1.27821786]

P값
 [ 0.67921787  1.12386617 -0.96806591]
Q값
 [ 1.05987639  0.04837771 -1.27821786]

P값
 [ 0.67902641  1.12374814 -0.96782012]
Q값
 [ 1.05969126  0.04824189 -1.27797722]

P값
 [ 0.8801926   0.53388225 -0.81502043]
Q값
 [ 1.56130279  1.63652266 -2.13923645]

P값
 [ 0.88010389  0.53382883 -0.81493809]
Q값
 [ 1.56130279  1.63652266 -2.13923645]

P값
 [-0.03421388  0.67704894 -2.33746521]
Q값
 [-0.638314    0.45817622 -1.98795172]

P값
 [-0.03403386  0.67698928 -2.33744444]
Q값
 [-0.638314    0.45817622 -1.98795172]

P값
 [-0.03408163  0.67692736 -2.33719367]
Q값
 [-0.638314    0.45


P값
 [ 0.6800164   1.12426599 -0.96728499]
Q값
 [ 1.05967304  0.04786735 -1.27903011]

P값
 [ 0.67982551  1.12414801 -0.96703993]
Q값
 [ 1.05948823  0.0477322  -1.27879006]

P값
 [ 0.87946341  0.53452796 -0.81542802]
Q값
 [ 1.56078207  1.63761733 -2.13811122]

P값
 [ 0.87937486  0.53447448 -0.81534575]
Q값
 [ 1.56078207  1.63761733 -2.13811122]

P값
 [-0.03436377  0.67550457 -2.33644429]
Q값
 [-0.6369451   0.45797079 -1.98916087]

P값
 [-0.03418402  0.67544497 -2.33642345]
Q값
 [-0.6369451   0.45797079 -1.98916087]

P값
 [-0.03423186  0.67538321 -2.33617276]
Q값
 [-0.6369451   0.45797079 -1.98916087]

P값
 [ 2.23393136  0.04114337 -1.25842275]
Q값
 [ 1.09892904 -0.13730405 -0.42775366]

P값
 [ 2.23394387  0.04114991 -1.25858172]
Q값
 [ 1.09892904 -0.13730405 -0.42775366]

P값
 [ 2.2339436   0.04112062 -1.25853005]
Q값
 [ 1.09892904 -0.13730405 -0.42775366]

P값
 [ 0.68023165  1.12453306 -0.96759273]
Q값
 [ 1.05966172  0.04783914 -1.27907509]

P값
 [ 0.68020459  1.12439115 -0.96736805]
Q값
 [ 1.05966172  0.04


P값
 [ 0.68099887  1.12479105 -0.96659268]
Q값
 [ 1.05945766  0.04733378 -1.2798818 ]

P값
 [ 0.68085494  1.1246881  -0.9664665 ]
Q값
 [ 1.05945766  0.04733378 -1.2798818 ]

P값
 [ 0.68066464  1.12457017 -0.96622221]
Q값
 [ 1.0592732   0.04719932 -1.27964235]

P값
 [ 0.87869748  0.53520896 -0.81585694]
Q값
 [ 1.5602351   1.63876731 -2.13691992]

P값
 [ 0.87860911  0.53515541 -0.81577474]
Q값
 [ 1.5602351   1.63876731 -2.13691992]

P값
 [-0.03452269  0.67388074 -2.33537456]
Q값
 [-0.63550599  0.45774959 -1.99043128]

P값
 [-0.03434323  0.67382119 -2.33535364]
Q값
 [-0.63550599  0.45774959 -1.99043128]

P값
 [-0.03439115  0.67375959 -2.33510303]
Q값
 [-0.63550599  0.45774959 -1.99043128]

P값
 [ 2.23260579  0.04029808 -1.25911359]
Q값
 [ 1.09931237 -0.13815618 -0.42793311]

P값
 [ 2.23261827  0.04030458 -1.25927256]
Q값
 [ 1.09931237 -0.13815618 -0.42793311]

P값
 [ 2.23261828  0.04027542 -1.25922086]
Q값
 [ 1.09931237 -0.13815618 -0.42793311]

P값
 [ 0.68107018  1.12495516 -0.96677425]
Q값
 [ 1.05944631  0.04

 [ 2.23128796  0.03945406 -1.25980269]
Q값
 [ 1.09969008 -0.13900541 -0.42811589]

P값
 [ 2.23130042  0.03946052 -1.25996165]
Q값
 [ 1.09969008 -0.13900541 -0.42811589]

P값
 [ 2.23130071  0.03943148 -1.25990992]
Q값
 [ 1.09969008 -0.13900541 -0.42811589]

P값
 [ 0.68190425  1.1253773  -0.9659617 ]
Q값
 [ 1.05923017  0.04677775 -1.28077204]

P값
 [ 0.68187672  1.12523543 -0.9657374 ]
Q값
 [ 1.05923017  0.04677775 -1.28077204]

P값
 [ 0.6817328   1.12513248 -0.96561135]
Q값
 [ 1.05923017  0.04677775 -1.28077204]

P값
 [ 0.68154312  1.1250146  -0.96536787]
Q값
 [ 1.05904607  0.04664402 -1.28053323]

P값
 [ 0.87789541  0.53592515 -0.81630695]
Q값
 [ 1.55966227  1.63997177 -2.13566203]

P값
 [ 0.87780723  0.53587154 -0.81622484]
Q값
 [ 1.55966227  1.63997177 -2.13566203]

P값
 [-0.03469073  0.67217842 -2.33425721]
Q값
 [-0.63399756  0.45751196 -1.99176201]

P값
 [-0.03451157  0.67211894 -2.33423622]
Q값
 [-0.63399756  0.45751196 -1.99176201]

P값
 [-0.03455958  0.6720575  -2.33398568]
Q값
 [-0.63399756  0.457511


P값
 [ 0.68256222  1.12555466 -0.964805  ]
Q값
 [ 1.05901334  0.04625481 -1.28161187]

P값
 [ 0.68237312  1.12543683 -0.96456228]
Q값
 [ 1.05882958  0.04612177 -1.28137365]

P값
 [ 0.8771374   0.53660492 -0.81673307]
Q값
 [ 1.55912087  1.6411103  -2.13446344]

P값
 [ 0.87704938  0.53655124 -0.81665103]
Q값
 [ 1.55912087  1.6411103  -2.13446344]

P값
 [-0.03485106  0.6705678  -2.3332039 ]
Q값
 [-0.63257062  0.45728174 -1.99302003]

P값
 [-0.03467218  0.67050839 -2.33318284]
Q값
 [-0.63257062  0.45728174 -1.99302003]

P값
 [-0.03472028  0.67044711 -2.33293238]
Q값
 [-0.63257062  0.45728174 -1.99302003]

P값
 [ 2.22990906  0.038567   -1.26052615]
Q값
 [ 1.10008164 -0.13989619 -0.42831188]

P값
 [ 2.22992151  0.03857342 -1.26068511]
Q값
 [ 1.10008164 -0.13989619 -0.42831188]

P값
 [ 2.22992208  0.03854451 -1.26063335]
Q값
 [ 1.10008164 -0.13989619 -0.42831188]

P값
 [ 0.68277744  1.12582168 -0.96511276]
Q값
 [ 1.05900191  0.04622743 -1.28165591]

P값
 [ 0.68274966  1.12567983 -0.96488866]
Q값
 [ 1.05900191  0.04

 [-0.03502054  0.66887933 -2.33210368]
Q값
 [-0.63107492  0.45703473 -1.99433779]

P값
 [-0.03484195  0.66881998 -2.33208254]
Q값
 [-0.63107492  0.45703473 -1.99433779]

P값
 [-0.03489014  0.66875887 -2.33183216]
Q값
 [-0.63107492  0.45703473 -1.99433779]

P값
 [ 2.2285386   0.03768139 -1.26124768]
Q값
 [ 1.10046707 -0.14078374 -0.42851151]

P값
 [ 2.22855102  0.03768777 -1.26140663]
Q값
 [ 1.10046707 -0.14078374 -0.42851151]

P값
 [ 2.22855189  0.03765899 -1.26135484]
Q값
 [ 1.10046707 -0.14078374 -0.42851151]

P값
 [ 0.68364574  1.12626605 -0.96427028]
Q값
 [ 1.05877289  0.04568275 -1.28253346]

P값
 [ 0.68361771  1.12612421 -0.96404639]
Q값
 [ 1.05877289  0.04568275 -1.28253346]

P값
 [ 0.68347382  1.12602126 -0.96392057]
Q값
 [ 1.05877289  0.04568275 -1.28253346]

P값
 [ 0.68328537  1.12590348 -0.96367869]
Q값
 [ 1.0585895   0.04555047 -1.28229589]

P값
 [ 0.87630404  0.53735553 -0.81720244]
Q값
 [ 1.5585256   1.64236227 -2.13313469]

P값
 [ 0.87621622  0.53730179 -0.81712048]
Q값
 [ 1.5585256   1.642362

 [-0.03505215  0.66716156 -2.33079498]
Q값
 [-0.62966     0.4567957  -1.99558356]

P값
 [ 2.22724439  0.03684141 -1.26193133]
Q값
 [ 1.10082757 -0.14162391 -0.4287045 ]

P값
 [ 2.22725679  0.03684776 -1.26209028]
Q값
 [ 1.10082757 -0.14162391 -0.4287045 ]

P값
 [ 2.22725793  0.0368191  -1.26203846]
Q값
 [ 1.10082757 -0.14162391 -0.4287045 ]

P값
 [ 0.68446613  1.12668815 -0.96347589]
Q값
 [ 1.05855465  0.04517047 -1.28336133]

P값
 [ 0.68443787  1.12654633 -0.96325219]
Q값
 [ 1.05855465  0.04517047 -1.28336133]

P값
 [ 0.68429399  1.12644338 -0.96312648]
Q값
 [ 1.05855465  0.04517047 -1.28336133]

P값
 [ 0.68410611  1.12632564 -0.96288536]
Q값
 [ 1.0583716   0.04503886 -1.28312434]

P값
 [ 0.87555407  0.53803402 -0.81762566]
Q값
 [ 1.55798983  1.64348925 -2.13192896]

P값
 [ 0.87546641  0.53798022 -0.81754377]
Q값
 [ 1.55798983  1.64348925 -2.13192896]

P값
 [-0.03519071  0.66719789 -2.33101212]
Q값
 [-0.62958569  0.456783   -1.99564896]

P값
 [-0.03501242  0.6671386  -2.33099091]
Q값
 [-0.62958569  0.456783

 [ 1.05833577  0.04466315 -1.28418358]

P값
 [ 0.68492249  1.12674772 -0.96209778]
Q값
 [ 1.05815306  0.04453221 -1.28394718]

P값
 [ 0.87480788  0.53871191 -0.81804749]
Q값
 [ 1.55745671  1.6446108  -2.13071995]

P값
 [ 0.87472039  0.53865803 -0.81796568]
Q값
 [ 1.55745671  1.6446108  -2.13071995]

P값
 [-0.035353    0.665607   -2.32998308]
Q값
 [-0.62817687  0.45653954 -1.9968885 ]

P값
 [-0.03517498  0.66554778 -2.3299618 ]
Q값
 [-0.62817687  0.45653954 -1.9968885 ]

P값
 [-0.03522333  0.665487   -2.32971156]
Q값
 [-0.62817687  0.45653954 -1.9968885 ]

P값
 [ 2.22589012  0.03595866 -1.26264908]
Q값
 [ 1.10120115 -0.14250512 -0.42891113]

P값
 [ 2.22590251  0.03596498 -1.26280802]
Q값
 [ 1.10120115 -0.14250512 -0.42891113]

P값
 [ 2.22590393  0.03593645 -1.26275617]
Q값
 [ 1.10120115 -0.14250512 -0.42891113]

P값
 [ 0.68532498  1.12713239 -0.96264591]
Q값
 [ 1.05832424  0.04463659 -1.28422671]

P값
 [ 0.68529647  1.12699059 -0.96242241]
Q값
 [ 1.05832424  0.04463659 -1.28422671]

P값
 [ 0.68515261  1.12688


P값
 [ 0.87393918  0.53937086 -0.81840829]
Q값
 [ 1.55689838  1.64578558 -2.12944386]

P값
 [-0.03552445  0.66393916 -2.32890817]
Q값
 [-0.62670012  0.45627878 -1.99818692]

P값
 [-0.03534672  0.66388001 -2.32888681]
Q값
 [-0.62670012  0.45627878 -1.99818692]

P값
 [-0.03539516  0.6638194  -2.32863665]
Q값
 [-0.62670012  0.45627878 -1.99818692]

P값
 [ 2.22454406  0.03507742 -1.2633649 ]
Q값
 [ 1.10156872 -0.14338306 -0.42912131]

P값
 [ 2.22455642  0.0350837  -1.26352384]
Q값
 [ 1.10156872 -0.14338306 -0.42912131]

P값
 [ 2.22455813  0.03505531 -1.26347196]
Q값
 [ 1.10156872 -0.14338306 -0.42912131]

P값
 [ 0.68617903  1.12757651 -0.96182226]
Q값
 [ 1.05809314  0.04410814 -1.28508592]

P값
 [ 0.68615027  1.12743472 -0.96159897]
Q값
 [ 1.05809314  0.04410814 -1.28508592]

P값
 [ 0.68600643  1.12733177 -0.9614735 ]
Q값
 [ 1.05809314  0.04410814 -1.28508592]

P값
 [ 0.68581975  1.12721412 -0.96123395]
Q값
 [ 1.0579108   0.04397794 -1.28485015]

P값
 [ 0.87398753  0.53946043 -0.81851211]
Q값
 [ 1.55687054  1.64


P값
 [ 0.68691461  1.12783432 -0.96086325]
Q값
 [ 1.05788459  0.04363713 -1.28585399]

P값
 [ 0.68677078  1.12773137 -0.96073789]
Q값
 [ 1.05788459  0.04363713 -1.28585399]

P값
 [ 0.68658464  1.12761375 -0.96049903]
Q값
 [ 1.05770257  0.04350756 -1.28561876]

P값
 [ 0.87328802  0.54010142 -0.81890901]
Q값
 [ 1.55637065  1.64689614 -2.12822836]

P값
 [ 0.87320088  0.54004742 -0.81882735]
Q값
 [ 1.55637065  1.64689614 -2.12822836]

P값
 [-0.03568791  0.66236112 -2.32789479]
Q값
 [-0.62530307  0.45602684 -1.99941442]

P값
 [-0.03551045  0.66230204 -2.32787337]
Q값
 [-0.62530307  0.45602684 -1.99941442]

P값
 [-0.03555898  0.66224158 -2.32762328]
Q값
 [-0.62530307  0.45602684 -1.99941442]

P값
 [ 2.22327281  0.03424165 -1.26404315]
Q값
 [ 1.10191239 -0.14421407 -0.42932424]

P값
 [ 2.22328516  0.0342479  -1.26420207]
Q값
 [ 1.10191239 -0.14421407 -0.42932424]

P값
 [ 2.22328713  0.03421962 -1.26415016]
Q값
 [ 1.10191239 -0.14421407 -0.42932424]

P값
 [ 0.68698594  1.12799828 -0.96104562]
Q값
 [ 1.05787299  0.04


P값
 [ 0.68757342  1.12815301 -0.95996689]
Q값
 [ 1.05766389  0.04314462 -1.28665941]

P값
 [ 0.68738784  1.12803543 -0.95972877]
Q값
 [ 1.0574822   0.04301571 -1.28642473]

P값
 [ 0.87255329  0.54077742 -0.81932659]
Q값
 [ 1.55584551  1.64800141 -2.12700981]

P값
 [ 0.87246632  0.54072335 -0.819245  ]
Q값
 [ 1.55584551  1.64800141 -2.12700981]

P값
 [-0.03585191  0.66078929 -2.32688895]
Q값
 [-0.62391172  0.45577085 -2.00063609]

P값
 [-0.03567471  0.66073028 -2.32686745]
Q값
 [-0.62391172  0.45577085 -2.00063609]

P값
 [-0.03572333  0.66066997 -2.32661743]
Q값
 [-0.62391172  0.45577085 -2.00063609]

P값
 [ 2.22200883  0.03340726 -1.26471965]
Q값
 [ 1.10225071 -0.14504211 -0.42953031]

P값
 [ 2.22202116  0.03341349 -1.26487857]
Q값
 [ 1.10225071 -0.14504211 -0.42953031]

P값
 [ 2.2220234   0.03338533 -1.26482663]
Q값
 [ 1.10225071 -0.14504211 -0.42953031]

P값
 [ 0.68778856  1.1284199  -0.96027461]
Q값
 [ 1.05765226  0.04311883 -1.28670165]

P값
 [ 0.68775935  1.12827815 -0.96005171]
Q값
 [ 1.05765226  0.04


P값
 [ 0.68851557  1.12867743 -0.95932662]
Q값
 [ 1.05744264  0.04265685 -1.2874594 ]

P값
 [ 0.68837179  1.12857447 -0.95920148]
Q값
 [ 1.05744264  0.04265685 -1.2874594 ]

P값
 [ 0.68818676  1.12845693 -0.9589641 ]
Q값
 [ 1.05726128  0.04252859 -1.28722528]

P값
 [ 0.87182228  0.5414528  -0.81974277]
Q값
 [ 1.55532296  1.64910143 -2.12578828]

P값
 [ 0.87173547  0.54139867 -0.81966125]
Q값
 [ 1.55532296  1.64910143 -2.12578828]

P값
 [-0.03601642  0.65922363 -2.32589056]
Q값
 [-0.62252601  0.45551085 -2.00185198]

P값
 [-0.0358395   0.65916468 -2.32586899]
Q값
 [-0.62252601  0.45551085 -2.00185198]

P값
 [-0.03588819  0.65910453 -2.32561904]
Q값
 [-0.62252601  0.45551085 -2.00185198]

P값
 [ 2.22075204  0.03257428 -1.26539442]
Q값
 [ 1.10258373 -0.14586718 -0.4297395 ]

P값
 [ 2.22076435  0.03258047 -1.26555333]
Q값
 [ 1.10258373 -0.14586718 -0.4297395 ]

P값
 [ 2.22076686  0.03255244 -1.26550137]
Q값
 [ 1.10258373 -0.14586718 -0.4297395 ]

P값
 [ 0.68858691  1.12884133 -0.95950918]
Q값
 [ 1.05743098  0.04


P값
 [ 2.21958303  0.03176469 -1.26613899]
Q값
 [ 1.10289436 -0.14664608 -0.42994053]

P값
 [ 0.68933933  1.12924039 -0.95878917]
Q값
 [ 1.05722085  0.04217376 -1.288254  ]

P값
 [ 0.68930967  1.12909868 -0.95856666]
Q값
 [ 1.05722085  0.04217376 -1.288254  ]

P값
 [ 0.68916591  1.12899572 -0.95844163]
Q값
 [ 1.05722085  0.04217376 -1.288254  ]

P값
 [ 0.68898143  1.12887821 -0.95820497]
Q값
 [ 1.05703982  0.04204615 -1.28802043]

P값
 [ 0.87109497  0.54212755 -0.82015754]
Q값
 [ 1.55480296  1.65019624 -2.12456384]

P값
 [ 0.87100832  0.54207335 -0.82007609]
Q값
 [ 1.55480296  1.65019624 -2.12456384]

P값
 [-0.03618143  0.65766411 -2.32489955]
Q값
 [-0.62114591  0.45524691 -2.00306211]

P값
 [-0.03600477  0.65760523 -2.32487792]
Q값
 [-0.62114591  0.45524691 -2.00306211]

P값
 [-0.03605355  0.65754523 -2.32462804]
Q값
 [-0.62114591  0.45524691 -2.00306211]

P값
 [ 2.21950239  0.03174272 -1.26606746]
Q값
 [ 1.10291147 -0.14668927 -0.42995178]

P값
 [ 2.21951468  0.03174888 -1.26622636]
Q값
 [ 1.10291147 -0.14

 [ 2.21832503  0.03095624 -1.26670348]
Q값
 [ 1.10321714 -0.14746534 -0.43015571]

P값
 [ 2.2183373   0.03096238 -1.26686238]
Q값
 [ 1.10321714 -0.14746534 -0.43015571]

P값
 [ 2.21834032  0.03093458 -1.26681036]
Q값
 [ 1.10321714 -0.14746534 -0.43015571]

P값
 [ 0.69012943  1.12966138 -0.95803452]
Q값
 [ 1.05699854  0.0416953  -1.28904327]

P값
 [ 0.69009954  1.1295197  -0.95781221]
Q값
 [ 1.05699854  0.0416953  -1.28904327]

P값
 [ 0.68995581  1.12941673 -0.95768729]
Q값
 [ 1.05699854  0.0416953  -1.28904327]

P값
 [ 0.68977187  1.12929926 -0.95745136]
Q값
 [ 1.05681783  0.04156833 -1.28881025]

P값
 [ 0.87037134  0.54280167 -0.8205709 ]
Q값
 [ 1.55428552  1.65128587 -2.12333656]

P값
 [ 0.87028486  0.54274741 -0.82048952]
Q값
 [ 1.55428552  1.65128587 -2.12333656]

P값
 [-0.03634692  0.65611069 -2.32391588]
Q값
 [-0.61977139  0.45497905 -2.00426652]

P값
 [-0.03617052  0.65605188 -2.32389417]
Q값
 [-0.61977139  0.45497905 -2.00426652]

P값
 [-0.03621939  0.65599204 -2.32364435]
Q값
 [-0.61977139  0.454979


P값
 [ 0.86960286  0.5433854  -0.82087989]
Q값
 [ 1.55379764  1.65231342 -2.12217132]

P값
 [-0.03650412  0.65464463 -2.32299066]
Q값
 [-0.61847432  0.45472174 -2.00540229]

P값
 [-0.03632797  0.65458588 -2.3229689 ]
Q값
 [-0.61847432  0.45472174 -2.00540229]

P값
 [-0.03637691  0.65452619 -2.32271914]
Q값
 [-0.61847432  0.45472174 -2.00540229]

P값
 [ 2.21708909  0.03012748 -1.26737316]
Q값
 [ 1.10353473 -0.1482816  -0.43037392]

P값
 [ 2.21710133  0.03013359 -1.26753204]
Q값
 [ 1.10353473 -0.1482816  -0.43037392]

P값
 [ 2.21710462  0.03010591 -1.26747999]
Q값
 [ 1.10353473 -0.1482816  -0.43037392]

P값
 [ 0.69091532  1.13008212 -0.95728534]
Q값
 [ 1.05677573  0.04122142 -1.28982723]

P값
 [ 0.6908852   1.12994046 -0.95706323]
Q값
 [ 1.05677573  0.04122142 -1.28982723]

P값
 [ 0.6907415   1.12983749 -0.95693843]
Q값
 [ 1.05677573  0.04122142 -1.28982723]

P값
 [ 0.69055811  1.12972005 -0.95670321]
Q값
 [ 1.05659535  0.04109509 -1.28959476]

P값
 [ 0.86965139  0.54347515 -0.82098285]
Q값
 [ 1.5537706   1.65


P값
 [ 0.86897269  0.5441126  -0.82137181]
Q값
 [ 1.55328511  1.6533931  -2.1209387 ]

P값
 [ 0.86888652  0.54405822 -0.82129056]
Q값
 [ 1.55328511  1.6533931  -2.1209387 ]

P값
 [-0.03667049  0.653103   -2.32202105]
Q값
 [-0.61711056  0.45444642 -2.00659563]

P값
 [-0.03649459  0.65304432 -2.32199922]
Q값
 [-0.61711056  0.45444642 -2.00659563]

P값
 [-0.03654362  0.65298478 -2.32174953]
Q값
 [-0.61711056  0.45444642 -2.00659563]

P값
 [ 2.21586009  0.02930018 -1.26804111]
Q값
 [ 1.10384716 -0.14909486 -0.43059515]

P값
 [ 2.21587232  0.02930627 -1.26819998]
Q값
 [ 1.10384716 -0.14909486 -0.43059515]

P값
 [ 2.21587586  0.0292787  -1.26814791]
Q값
 [ 1.10384716 -0.14909486 -0.43059515]

P값
 [ 0.69169703  1.13050258 -0.95654159]
Q값
 [ 1.05655243  0.04075205 -1.29060595]

P값
 [ 0.69166668  1.13036094 -0.95631969]
Q값
 [ 1.05655243  0.04075205 -1.29060595]

P값
 [ 0.69152301  1.13025797 -0.95619499]
Q값
 [ 1.05655243  0.04075205 -1.29060595]

P값
 [ 0.69134015  1.13014055 -0.95596048]
Q값
 [ 1.05637237  0.04

### iteration step :  900  rmse :  0.015130183385497422

P값
 [ 0.86828611  0.5446243  -0.82163529]
Q값
 [ 1.55285543  1.65429838 -2.11989866]
### iteration step :  900  rmse :  0.015213149328052154

P값
 [-0.03681091  0.65180945 -2.32121007]
Q값
 [-0.61596638  0.45421166 -2.00759619]
### iteration step :  900  rmse :  0.015047354438883272

P값
 [-0.03663523  0.65175082 -2.32118818]
Q값
 [-0.61596638  0.45421166 -2.00759619]
### iteration step :  900  rmse :  0.015008344458784826

P값
 [-0.03668433  0.65169141 -2.32093854]
Q값
 [-0.61596638  0.45421166 -2.00759619]
### iteration step :  900  rmse :  0.015131953783816456

P값
 [ 2.2148305   0.02860464 -1.26860226]
Q값
 [ 1.10410628 -0.14977738 -0.43078376]
### iteration step :  900  rmse :  0.015145679749104263

P값
 [ 2.2148427   0.02861071 -1.26876112]
Q값
 [ 1.10410628 -0.14977738 -0.43078376]
### iteration step :  900  rmse :  0.014975180991932424

P값
 [ 2.21484646  0.02858325 -1.26870902]
Q값
 [ 1.10410628 -0.14977738 -0.43078376]
### iteration

 [-0.03691642  0.65084206 -2.32060512]
Q값
 [-0.61511078  0.45403384 -2.008344  ]

P값
 [-0.0367409   0.65078348 -2.32058319]
Q값
 [-0.61511078  0.45403384 -2.008344  ]

P값
 [-0.03679005  0.65072416 -2.32033359]
Q값
 [-0.61511078  0.45403384 -2.008344  ]

P값
 [ 2.21406148  0.02808368 -1.26902232]
Q값
 [ 1.10429825 -0.15028787 -0.43092659]

P값
 [ 2.21407367  0.02808974 -1.26918117]
Q값
 [ 1.10429825 -0.15028787 -0.43092659]

P값
 [ 2.2140776   0.02806235 -1.26912906]
Q값
 [ 1.10429825 -0.15028787 -0.43092659]

P값
 [ 0.69284144  1.13112164 -0.95545536]
Q값
 [ 1.05622251  0.04006849 -1.29174405]

P값
 [ 0.69281076  1.13098003 -0.95523376]
Q값
 [ 1.05622251  0.04006849 -1.29174405]

P값
 [ 0.69266713  1.13087705 -0.95510922]
Q값
 [ 1.05622251  0.04006849 -1.29174405]

P값
 [ 0.69248506  1.13075969 -0.95487576]
Q값
 [ 1.05604294  0.03994372 -1.2915129 ]

P값
 [ 0.86788609  0.54513839 -0.82199578]
Q값
 [ 1.55250762  1.6550313  -2.11905228]

P값
 [ 0.86780017  0.5450839  -0.82191464]
Q값
 [ 1.55250762  1.655031


P값
 [-0.03688203  0.64949738 -2.3197809 ]
Q값
 [-0.61397334  0.45379447 -2.0093376 ]

P값
 [-0.03693125  0.64943819 -2.31953136]
Q값
 [-0.61397334  0.45379447 -2.0093376 ]

P값
 [ 2.21304034  0.02739    -1.26958134]
Q값
 [ 1.10455106 -0.15096665 -0.43111887]

P값
 [ 2.21305252  0.02739604 -1.26974018]
Q값
 [ 1.10455106 -0.15096665 -0.43111887]

P값
 [ 2.21305666  0.02736874 -1.26968805]
Q값
 [ 1.10455106 -0.15096665 -0.43111887]

P값
 [ 0.69349136  1.13147507 -0.95483986]
Q값
 [ 1.05603356  0.03968218 -1.29238936]

P값
 [ 0.69346049  1.13133348 -0.95461844]
Q값
 [ 1.05603356  0.03968218 -1.29238936]

P값
 [ 0.69331688  1.1312305  -0.95449399]
Q값
 [ 1.05603356  0.03968218 -1.29238936]

P값
 [ 0.69313526  1.13111316 -0.95426112]
Q값
 [ 1.05585425  0.03955793 -1.29215865]

P값
 [ 0.86729019  0.54570369 -0.82233862]
Q값
 [ 1.55208114  1.65593014 -2.11800895]

P값
 [ 0.8672044   0.54564916 -0.82225753]
Q값
 [ 1.55208114  1.65593014 -2.11800895]

P값
 [-0.03706615  0.64947566 -2.31975292]
Q값
 [-0.61390237  0.45


P값
 [ 2.21196063  0.02665413 -1.27017396]
Q값
 [ 1.10481576 -0.15168551 -0.43132542]

P값
 [ 2.21197278  0.02666015 -1.27033279]
Q값
 [ 1.10481576 -0.15168551 -0.43132542]

P값
 [ 2.21197716  0.02663296 -1.27028064]
Q값
 [ 1.10481576 -0.15168551 -0.43132542]

P값
 [ 0.6941787   1.13185031 -0.95419001]
Q값
 [ 1.05583246  0.0392751  -1.29307103]

P값
 [ 0.69414763  1.13170875 -0.95396878]
Q값
 [ 1.05583246  0.0392751  -1.29307103]

P값
 [ 0.69400405  1.13160576 -0.95384443]
Q값
 [ 1.05583246  0.0392751  -1.29307103]

P값
 [ 0.6938229   1.13148844 -0.95361218]
Q값
 [ 1.05565344  0.03915141 -1.29284079]

P값
 [ 0.86665984  0.54630382 -0.82270177]
Q값
 [ 1.5516299   1.6568813  -2.11689848]

P값
 [ 0.8665742   0.54624923 -0.82262075]
Q값
 [ 1.5516299   1.6568813  -2.11689848]

P값
 [-0.03721619  0.648114   -2.3189063 ]
Q값
 [-0.61269829  0.45352209 -2.0104507 ]

P값
 [-0.03704112  0.64805554 -2.31888424]
Q값
 [-0.61269829  0.45352209 -2.0104507 ]

P값
 [-0.03709043  0.6479965  -2.31863476]
Q값
 [-0.61269829  0.45

 [ 0.86598368  0.54681352 -0.82296155]
Q값
 [ 1.551207    1.65777291 -2.11585156]

P값
 [-0.03735766  0.64683675 -2.31811454]
Q값
 [-0.61156895  0.45327724 -2.01143595]

P값
 [-0.03718281  0.64677835 -2.31809243]
Q값
 [-0.61156895  0.45327724 -2.01143595]

P값
 [-0.03723218  0.64671944 -2.317843  ]
Q값
 [-0.61156895  0.45327724 -2.01143595]

P값
 [ 2.21088628  0.02591947 -1.27076521]
Q값
 [ 1.10507646 -0.15240195 -0.4315343 ]

P값
 [ 2.21089841  0.02592547 -1.27092404]
Q값
 [ 1.10507646 -0.15240195 -0.4315343 ]

P값
 [ 2.21090301  0.02589839 -1.27087186]
Q값
 [ 1.10507646 -0.15240195 -0.4315343 ]

P값
 [ 0.69486276  1.13222526 -0.95354438]
Q값
 [ 1.05563103  0.03887147 -1.29374864]

P값
 [ 0.69483149  1.13208371 -0.95332333]
Q값
 [ 1.05563103  0.03887147 -1.29374864]

P값
 [ 0.69468795  1.13198072 -0.95319908]
Q값
 [ 1.05563103  0.03887147 -1.29374864]

P값
 [ 0.69450726  1.13186343 -0.95296745]
Q값
 [ 1.0554523   0.03874833 -1.29351886]

P값
 [ 0.86603236  0.54690342 -0.82306378]
Q값
 [ 1.55118063  1.657828


P값
 [ 0.69554357  1.1325999  -0.95290294]
Q값
 [ 1.05542929  0.03847126 -1.29442222]

P값
 [ 0.6955121   1.13245837 -0.95268208]
Q값
 [ 1.05542929  0.03847126 -1.29442222]

P값
 [ 0.69536858  1.13235537 -0.95255792]
Q값
 [ 1.05542929  0.03847126 -1.29442222]

P값
 [ 0.69518836  1.1322381  -0.95232691]
Q값
 [ 1.05525084  0.03834866 -1.2941929 ]

P값
 [ 0.86540774  0.5475025  -0.82342464]
Q값
 [ 1.55073329  1.65877182 -2.11467176]

P값
 [ 0.86532237  0.54744779 -0.82334374]
Q값
 [ 1.55073329  1.65877182 -2.11467176]

P값
 [-0.03751712  0.64540482 -2.31722963]
Q값
 [-0.61030297  0.45299876 -2.01253968]

P값
 [-0.0373425   0.64534649 -2.31720746]
Q값
 [-0.61030297  0.45299876 -2.01253968]

P값
 [-0.03739195  0.64528771 -2.31695808]
Q값
 [-0.61030297  0.45299876 -2.01253968]

P값
 [ 2.20975452  0.02514294 -1.27138976]
Q값
 [ 1.10534815 -0.15315789 -0.43175797]

P값
 [ 2.20976663  0.02514892 -1.27154857]
Q값
 [ 1.10534815 -0.15315789 -0.43175797]

P값
 [ 2.20977148  0.02512194 -1.27149636]
Q값
 [ 1.10534815 -0.15

 [-0.03749359  0.64399898 -2.31637726]
Q값
 [-0.6091117   0.45273285 -2.01357758]

P값
 [-0.03754312  0.64394034 -2.31612794]
Q값
 [-0.6091117   0.45273285 -2.01357758]

P값
 [ 2.20869107  0.02441081 -1.27197819]
Q값
 [ 1.10560068 -0.15386933 -0.43197156]

P값
 [ 2.20870317  0.02441677 -1.27213699]
Q값
 [ 1.10560068 -0.15386933 -0.43197156]

P값
 [ 2.20870824  0.0243899  -1.27208477]
Q값
 [ 1.10560068 -0.15386933 -0.43197156]

P값
 [ 0.69626088  1.13299621 -0.95222829]
Q값
 [ 1.05521535  0.03805118 -1.29513105]

P값
 [ 0.6962292   1.13285471 -0.95200764]
Q값
 [ 1.05521535  0.03805118 -1.29513105]

P값
 [ 0.69608572  1.1327517  -0.95188358]
Q값
 [ 1.05521535  0.03805118 -1.29513105]

P값
 [ 0.69590598  1.13263446 -0.95165322]
Q값
 [ 1.05503719  0.03792916 -1.29490221]

P값
 [ 0.86474947  0.54813624 -0.82380547]
Q값
 [ 1.55026175  1.65976636 -2.11348989]

P값
 [ 0.86466426  0.54808147 -0.82372463]
Q값
 [ 1.55026175  1.65976636 -2.11348989]

P값
 [-0.03767687  0.64397812 -2.31635083]
Q값
 [-0.60904175  0.452717

In [14]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.991 1.38  1.227 2.    1.636]
 [5.905 4.977 0.86  2.984 1.003]
 [6.153 1.227 2.987 3.978 3.986]
 [4.97  2.005 1.006 2.009 1.349]]
