In [3]:
import numpy as np

R = np.array([[4, np.NaN, np.NaN, 2, np.NaN],
              [np.NaN, 5, np.NaN, 3, 1],
              [np.NaN, np.NaN, 3, 4, 4],
              [5, 2, 1, 2, np.NaN]])
num_users, num_items = R.shape
K=3

np.random.seed(1)
P = np.random.normal(scale=1./K, size=(num_users, K))
Q = np.random.normal(scale=1./K, size=(num_items, K))

In [4]:
from sklearn.metrics import mean_squared_error

In [8]:
def get_rmse(R, P, Q, non_zeros):
    error = 0
    
    full_pred_matrix = np.dot(P, Q.T)
    
    x_non_zero_ind = [non_zero[0] for non_zero in non_zeros]
    y_non_zero_ind = [non_zero[1] for non_zero in non_zeros]
    R_non_zeros = R[x_non_zero_ind, y_non_zero_ind]
    full_pred_matrix_non_zeros = full_pred_matrix[x_non_zero_ind, y_non_zero_ind]
    mse = mean_squared_error(R_non_zeros, full_pred_matrix_non_zeros)
    rmse = np.sqrt(mse)
    
    return rmse

In [11]:
non_zeros = [(i,j,R[i,j]) for i in range(num_users) for j in range(num_items) if R[i,j] > 0]

steps=1000
learning_rate = 0.01
r_lambda = 0.01

for step in range(steps):
    for i, j, r in non_zeros:
        eij = r - np.dot(P[i, :], Q[j, :].T)
        
        P[i, :] = P[i, :] + learning_rate*(eij * Q[j,:] - r_lambda*P[i, :])
        Q[j, :] = Q[j, :] + learning_rate*(eij * P[i,:] - r_lambda*Q[j, :])
        
        rmse = get_rmse(R, P, Q, non_zeros)
        if (step % 50) == 0:
            print('### iteration step : ', step, " rmse : ", rmse)

### iteration step :  0  rmse :  3.232455939981293
### iteration step :  0  rmse :  3.2315985246182577
### iteration step :  0  rmse :  3.2247307461897132
### iteration step :  0  rmse :  3.222896885581507
### iteration step :  0  rmse :  3.2230943095568962
### iteration step :  0  rmse :  3.221766134233418
### iteration step :  0  rmse :  3.219841084710466
### iteration step :  0  rmse :  3.2180261567201343
### iteration step :  0  rmse :  3.21300300044208
### iteration step :  0  rmse :  3.211258781425875
### iteration step :  0  rmse :  3.21135450472713
### iteration step :  0  rmse :  3.2099898005404466
### iteration step :  50  rmse :  0.48996188902825316
### iteration step :  50  rmse :  0.4896235008999994
### iteration step :  50  rmse :  0.4888570136076027
### iteration step :  50  rmse :  0.48865073101470424
### iteration step :  50  rmse :  0.48874337019392566
### iteration step :  50  rmse :  0.4880521595580434
### iteration step :  50  rmse :  0.48816487959267496
### iterat

### iteration step :  650  rmse :  0.018834120153215377
### iteration step :  650  rmse :  0.01873414958557135
### iteration step :  650  rmse :  0.018837529549766217
### iteration step :  650  rmse :  0.018854052311342122
### iteration step :  650  rmse :  0.018682755075855834
### iteration step :  650  rmse :  0.018664677996206223
### iteration step :  650  rmse :  0.01834285181703788
### iteration step :  650  rmse :  0.018445549382594264
### iteration step :  650  rmse :  0.018516696639247644
### iteration step :  650  rmse :  0.018819605241956583
### iteration step :  700  rmse :  0.018543695889728807
### iteration step :  700  rmse :  0.01861623250697151
### iteration step :  700  rmse :  0.018502378805867272
### iteration step :  700  rmse :  0.018406702602123147
### iteration step :  700  rmse :  0.018511193755915558
### iteration step :  700  rmse :  0.01852637017997126
### iteration step :  700  rmse :  0.018352655191512576
### iteration step :  700  rmse :  0.018335032894451

In [12]:
pred_matrix = np.dot(P, Q.T)
print('예측 행렬:\n', np.round(pred_matrix, 3))

예측 행렬:
 [[3.99  0.467 1.448 2.003 1.912]
 [6.693 4.979 0.894 2.979 1.003]
 [7.505 0.544 2.987 3.975 3.986]
 [4.966 2.004 1.008 2.022 1.219]]
